feat: add support for pattern matching in rule no-unexpected-wire-adapter-usages
salesforce/eslint-plugin-lwc pull request #95
Opened 2022-06-02 14:10 UTC by seckardt

2022-06-02 19:33 UTC, ekashida approved these changes
Implementation lgtm but would like to hear from @pmdartus whether there was a reason why this feature was added for [no-unknown-wire-adapters](https://github.com/salesforce/eslint-plugin-lwc/blob/3a48234683064c648f860b4b59e0531390bafdfb/lib/rules/no-unknown-wire-adapters.js) and not this plugin.

2022-06-03 08:56 UTC, pmdartus requested changes
The code change looks good. Please update the documentation in `docs/rules/no-unexpected-wire-adapter-usages.md` to reflect the addition of glob support.

2022-06-07 21:33 UTC, ekashida approved these changes

2022-06-08 08:57 UTC, pmdartus approved these changes

2022-06-08 09:00 UTC, merged